version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "beatngu13"
      - "martin-v"
      - "modulo11"
      - "diba1013"
